CREATE DATABASE tillter;

CREATE TABLE Users
(
  id INT AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  hash_pass VARCHAR(60) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Tweets
(
  id INT AUTO_INCREMENT,
  user_id INT NOT NULL,
  text TEXT NOT NULL,
  creation_date DATE NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES Users(id) ON DELETE CASCADE
);




CREATE TABLE Comments
(
id INT AUTO_INCREMENT,
user_id INT NOT NULL,
post_id INT NOT NULL,
creation_date DATETIME NOT NULL,
text TEXT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(user_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY(post_id) REFERENCES Tweets(id) ON DELETE CASCADE
);


CREATE TABLE Messages
(
id INT AUTO_INCREMENT,
send_id INT NOT NULL,
recive_id INT NOT NULL,
status INT NOT NULL,
text TEXT NOT NULL,
creation_date DATETIME NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(recive_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY(send_id) REFERENCES Users(id) ON DELETE CASCADE
);

